# Generated by Django 5.1.2 on 2024-11-29 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_categoryimagess'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='images',
            new_name='image',
        ),
    ]
