# Generated by Django 5.1.2 on 2024-11-29 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_rename_images_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoryimagess',
            old_name='images',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='imagess',
            old_name='images',
            new_name='image',
        ),
    ]
