# Generated by Django 5.1.2 on 2024-11-29 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_rename_images_categoryimagess_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='images',
            new_name='image',
        ),
    ]
