# Generated by Django 5.1.2 on 2024-12-05 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('keywords', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('adress', models.CharField(blank=True, max_length=250)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('fax', models.CharField(blank=True, max_length=15)),
                ('e_mail', models.CharField(blank=True, max_length=50)),
                ('smtpserver', models.CharField(blank=True, max_length=100)),
                ('smtpemail', models.CharField(blank=True, max_length=60)),
                ('smtppassword', models.CharField(blank=True, max_length=20)),
                ('smtpport', models.CharField(blank=True, max_length=20)),
                ('facebook', models.CharField(blank=True, max_length=60)),
                ('instagram', models.CharField(blank=True, max_length=40)),
                ('contact', models.CharField(blank=True, max_length=100)),
                ('aboutus', models.TextField(blank=True, max_length=250)),
                ('reference', models.TextField()),
                ('icon', models.ImageField(blank=True, upload_to='images/')),
                ('status', models.CharField(blank=True, choices=[('True', 'Evet'), ('False', 'Hayır')], max_length=20)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('upload_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
